#!/usr/bin/env node
"use strict";
const swarm = require('swarm-protocol');
const args = require('minimist')(process.argv.slice(2));
const cli = require('commander');

cli
    .version('0.0.1')
    .command("create [options] <path>", "create a database").alias('C')
    .command("db [options] <path>", "read/write from/to a database").alias('D')
    // .command("fork")
    .command("user [options] <path>", "create/edit users").alias('U')
    .command("run [options] <path>", "run a database (the default)", {isDefault: true}).alias('R')
    .parse(process.argv);
